name: modal_util
description: "Common modal and toast utility to bootstrap quickly"
version: 0.0.1
homepage: https://github.com/yourusername/bloc_error_handler

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1 
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: 